### ISSUE TITLE
Prefix tables

### ISSUE THREAD

**Issue by FlamesONE** [EFTEC/PdoOne#2]
Hello, i just started to use this library, and i have a problem.
I need to add prefix to every table in QueryBuilder.
I editing $prefixBase, but it's not working.
in your documentation $prefixBase defined as non-static var, but it's not it.
How i can add prefix to every table?

**Comment by jorgecc** [comment]
Ok, added a new field called $prefixTable

**Comment by FlamesONE** [comment]
Thanks for really quick solution
